[package]
name = "top_tree_compression"
version = "0.1.0"
authors = ["uzdlm <jan.ellmers@yahoo.de>"]

[dependencies]
xml-rs = "0.7"

[features]
default = ["performance_test"]
debug = []
performance_test = []